apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: storageclass-reader
rules:
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: storageclass-reader-binding
subjects:
- kind: ServiceAccount
  name: default
  # modify to namespace where mutant runs
  namespace: web
roleRef:
  kind: ClusterRole
  name: storageclass-reader
  apiGroup: rbac.authorization.k8s.io

